### ISSUE TITLE
[TASK]: Modify / Delete instances of the played games

### ISSUE THREAD

**Issue by Aniol0012** [Computer-Engineering-UdL/Game-Management#34]
### Detailed Description

Once there are played games added to the game-list, those games needs to be able to modify its details and even delete that game. This must be done from the details for that game. This issue depends on #33.

### Priority

Medium

**Comment by julianogales** [comment]
Right now, the user can't delete any games added to his library because there is no delete button:

![image](https://github.com/Computer-Engineering-UdL/Game-Management/assets/150971528/80fd018e-8fd9-4dbf-b91d-c91d567b58d8)

> **Suggestion from frontend:**
> Add a heart-shape button inside every game box of the user's library that stays active once the game is added, and when the user wants to remove the game just clicks on it. Only after confirming it to the system, the user can remove the game from his library.

**Comment by Aniol0012** [comment]
In progress 🥶
